version: 2.1

executors:
  ubuntu_1804:
    docker:
      - image: circleci/buildpack-deps:bionic
  macos_1015:
    macos:
      xcode: "12.4.0"
  macos_1106:
    macos:
      xcode: "13.1.0"

commands:
  setup_ubuntu:
    description: "Setup Ubuntu test environment"
    steps:
      - run:
          name: Setup test environment
          command: |
            sudo apt-get install lsb-release
  run_tests:
    description: "Tests"
    steps:
      - run:
          name: Bats Tests
          command: |
            make tests

jobs:
  test:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout
      - run_tests
  test_ubuntu_1804:
    executor: ubuntu_1804
    steps:
      - checkout
      - setup_ubuntu
      - run_tests

workflows:
  all-tests:
    jobs:
      - test_ubuntu_1804
      - test:
          matrix:
            parameters:
              os: [macos_1015, macos_1106]
