version: 2.1

executors:
  ubuntu_1804:
    docker:
      - image: cimg/base:current-18.04
  macos_1015:
    macos:
      xcode: "12.4.0"
  macos_1106:
    macos:
      xcode: "13.1.0"

commands:
  setup_ubuntu:
    description: "Setup Ubuntu test environment"
    steps:
      - run:
          name: Setup test environment
          command: |
            sudo apt-get install lsb-release
  setup_macos:
    description: "Setup Ubuntu test environment"
    steps:
      - run:
          name: Setup test environment
          command: |
            sudo launchctl limit maxfiles 24576
  run_tests:
    description: "Tests"
    steps:
      - run:
          name: Bats Tests
          command: |
            make tests

jobs:
  test_macos:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout
      - setup_macos
      - run_tests
  test_ubuntu:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout
      - setup_ubuntu
      - run_tests

workflows:
  all-tests:
    jobs:
      - test_ubuntu:
          matrix:
            parameters:
              os: [ubuntu_1804]
      - test_macos:
          matrix:
            parameters:
              os: [macos_1015, macos_1106]
